Update to 1.12.2, use BiliLiveLib, add overlay.
3TUSK/BiliLiveMonitor pull request #2
Opened 2018-08-01 07:36 UTC by cqjjjzr

Signed-off-by: Charlie Jiang <cqjjjzr@126.com>

2018-08-02 03:55 UTC, 3TUSK requested changes
3 (very) minor things. Also, do we need... internationalization & localization?

2018-08-02 03:55 UTC, 3TUSK commented on src/main/java/info/tritusk/projectbilistream/BiliLiveMonitor.java
> +import org.jetbrains.annotations.NotNull;
`javax.annotation.Nonnull`?

2018-08-02 03:55 UTC, 3TUSK commented on src/main/java/info/tritusk/projectbilistream/Command.java
> -		}
确定之前的线程可以直接丢弃？

2018-08-02 03:55 UTC, 3TUSK commented on src/main/java/info/tritusk/projectbilistream/Overlay.java
> + * @since rv1
`@since 0.0.1`

2018-08-02 04:01 UTC, cqjjjzr commented on src/main/java/info/tritusk/projectbilistream/BiliLiveMonitor.java
> +import org.jetbrains.annotations.NotNull;
This is JetBrains annotations, from BiliLiveLib.

2018-08-02 04:02 UTC, cqjjjzr commented on src/main/java/info/tritusk/projectbilistream/Command.java
> -		}
Yes. Just do it.

2018-08-02 04:05 UTC, cqjjjzr commented
I18n is unnecessary. I think only Chinese users will use this mod.

Also, 需要本地化的部分并不多。

2018-08-03 03:33 UTC, 3TUSK approved these changes

2018-08-03 03:33 UTC, merged